### ISSUE TITLE
Different ref_type support

### ISSUE THREAD

**Issue by joli-sys** [saidsef/terraform-aws-gitlab-oidc#40]
### Description of Problem:
`ref_type` is hardcoded as `branch` (https://github.com/saidsef/terraform-aws-gitlab-oidc/blob/main/current.tf#L21). It would be great if we can change `ref_type` based on some variable, or something like that. For example `ref_type:tag`

### Potential Solutions:
Add variable `ref_type`.

**Comment by joli-sys** [comment]
Possible solution here: https://github.com/saidsef/terraform-aws-gitlab-oidc/pull/41

**Comment by saidsef** [comment]
This is resolved in tag v2.2.0
